### ISSUE TITLE
does is support 'begin' and 'commit'

### ISSUE THREAD

**Issue by kxjhcs** [jayralencar/sqlite-sync.js#1]
does is support 'begin' and 'commit'? tks

**Comment by jayralencar** [comment]
Hi @kxjhcs ,
Not yet. But I'll implemt it in the next release.

**Comment by kxjhcs** [comment]
@jayralencar 
![image](https://cloud.githubusercontent.com/assets/9457045/15448643/694fa1b8-1f9a-11e6-889d-e733c00b0a86.png)

**Comment by jayralencar** [comment]
Hi @kxjhcs 
For now you can do this:
```js
sqlite.run("BEGIN; DELETE FROM COMPANYS WHERE ID = 6; ROLLBACK;");
```
I dont know if it will fix your problem.
Ok?
