### ISSUE TITLE
? substitution broken for strings using "?" character

### ISSUE THREAD

**Issue by roninski** [jayralencar/sqlite-sync.js#14]
Repro:
sqlite.run('CREATE TABLE IF NOT EXISTS things(id INTEGER PRIMARY KEY, word STR, things INT)');
sqlite.run("INSERT INTO things(id, word, things) VALUES (?, ?, ?)",[1, "???", 10]);

Expected: "INSERT INTO things(id, word, things) VALUES (1, '???', 10)"
Actual: "INSERT INTO things(id, word, things) VALUES (1, '10??', ?)"

Seems to be an issue due to the prevalance of this loop (e.g. sqlite.js line 233):
if(data){
    for(var i = 0 ; i < data.length; i++){
        sql = sql.replace('?',"'"+data[i]+"'");
    }
}

**Comment by jayralencar** [comment]
Hi @roninski, I will test it.

**Comment by jayralencar** [comment]
Fixed [here](https://github.com/jayralencar/sqlite-sync.js/commit/02c78a2fdb3c342fbc765c02a0e12fe394ba7f3a)
Try installing 0.3.7
