### ISSUE TITLE
Usar em projeto de grande porte

### ISSUE THREAD

**Issue by rodrigomartins50** [jayralencar/sqlite-sync.js#2]
Olá @jayralencar , ficou muito top seu framework, estou em um projeto onde estamos trabalhando com node-webkit, queria saber se seu framework já está no ponto para poder investir nele em um projeto de grande porte.

**Comment by jayralencar** [comment]
Olá @rodrigomartins50 o sqlite-sync é apenas um modulo de conexão com banco de dados SQLite e pode ser usado sim e projetos de grande porte, eu uso um módulo derivado dele que é o [sqlite-cipher](https://github.com/jayralencar/sqlite-cipher.js) em um projeto com RFID.

**Comment by rodrigomartins50** [comment]
vlw pela resposta rápida, mas então eu devo utilizar o sqlite-sync ou o sqlite-chipher?

**Comment by jayralencar** [comment]
sqlite-cipher é pra bancos criptografado, esta é a diferença.

**Comment by rodrigomartins50** [comment]
ok, vlw muito obrigado.
